front-build:
  stage: build
  tags:
    - docker
  image: node:14.17.3
  cache:
    key: node_modules
    paths:
      - client-angular/node_modules
  before_script:
    - cd client-angular
    - npm install
  script:
    - npm run build
  except:
    - develop

front-test:
  stage: test
  tags:
    - docker
  image: node:14.17.3
  cache:
    key: node_modules
    paths:
      - client-angular/node_modules
  before_script:
    - cd client-angular
    - npm install
  script:
    - echo "Test"
  except:
    - develop
    
deploy-dev:
  stage: deploy
  tags:
    - docker
  image: python:3.9.6
  cache:
    key: eb_installation
    paths:
      - /root/.pyenv/
      - /root/.ebcli-virtual-env/
      - /root/.profile

  before_script:
    - sh eb/install-eb.sh
    - source /root/.profile
    - eb --version
  script: 
    - echo "SCRIPT - Deploy on dev"
  only:
    - develop
