front-build:
  stage: build
  tags:
    - docker
  image: node:14.17.3
  before_script:
    - cd client-angular
    - npm install
  script:
    - npm run build

front-test:
  tags:
    - docker
  stage: test
  script: 
    - echo "Test"