
front-build:
  stage: build
  tags:
    - docker
  image: node:14.17.3
  cache:
    key: node_modules
    paths:
      - /client-angular/node_modules
  before_script:
    - cd client-angular
    - npm install
  script:
    - npm run build

front-test:
  tags:
    - docker
  stage: test
  before_script:
    - cd client-angular
    - npm install
  script:
    - npm test
    
deploy-dev:
  tags:
    - docker
  stage: test
  script: 
    - echo "Deploy"
  only:
    - develop
