branch-defaults:
  dev:
    environment: eb-poc-dev
  test:
    environment: eb-poc-test
environment-defaults:
  eb-poc-dev:
    branch: null
    repository: null
global:
  application_name: eb-poc
  default_ec2_keyname: aws-eb
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
